apiVersion: v1
kind: Service
metadata: # kpt-merge: /frontend-nodeport
  name: frontend-nodeport
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
